from PyQt5 import QtCore, QtGui, QtWidgets


class createAccount(object):

    def __init__(self):
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(280, 10, 291, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 71, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 130, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 141, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 270, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(660, 270, 71, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 350, 71, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 420, 71, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 490, 181, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 570, 141, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 650, 71, 31))
        self.label_11.setObjectName("label_11")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(90, 130, 301, 41))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(560, 130, 331, 41))
        self.password.setObjectName("password")
        self.sPhoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.sPhoneNumber.setGeometry(QtCore.QRect(160, 190, 221, 41))
        self.sPhoneNumber.setObjectName("sPhoneNumber")
        self.fName = QtWidgets.QLineEdit(self.centralwidget)
        self.fName.setGeometry(QtCore.QRect(90, 270, 201, 41))
        self.fName.setObjectName("fName")
        self.lName = QtWidgets.QLineEdit(self.centralwidget)
        self.lName.setGeometry(QtCore.QRect(420, 270, 191, 41))
        self.lName.setObjectName("lName")
        self.nName = QtWidgets.QLineEdit(self.centralwidget)
        self.nName.setGeometry(QtCore.QRect(730, 270, 191, 41))
        self.nName.setObjectName("nName")
        self.nationalID = QtWidgets.QLineEdit(self.centralwidget)
        self.nationalID.setGeometry(QtCore.QRect(80, 350, 201, 41))
        self.nationalID.setObjectName("nationalID")
        self.birthDate = QtWidgets.QLineEdit(self.centralwidget)
        self.birthDate.setGeometry(QtCore.QRect(80, 410, 151, 41))
        self.birthDate.setObjectName("birthDate")
        self.pPhoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.pPhoneNumber.setGeometry(QtCore.QRect(160, 490, 201, 41))
        self.pPhoneNumber.setObjectName("pPhoneNumber")
        self.defaultAccessStatus = QtWidgets.QLineEdit(self.centralwidget)
        self.defaultAccessStatus.setGeometry(QtCore.QRect(150, 570, 91, 41))
        self.defaultAccessStatus.setObjectName("defaultAccessStatus")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(80, 630, 591, 81))
        self.address.setObjectName("address")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(800, 620, 141, 91))
        self.submit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit.setObjectName("submit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.submit.clicked.connect(MainWindow.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Create account</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Username:"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.label_3.setText(_translate("MainWindow", "system phonr number:"))
        self.label_4.setText(_translate("MainWindow", "Fist name:"))
        self.label_5.setText(_translate("MainWindow", "Last name:"))
        self.label_6.setText(_translate("MainWindow", "Nick name:"))
        self.label_7.setText(_translate("MainWindow", "National id:"))
        self.label_8.setText(_translate("MainWindow", "Birth date:"))
        self.label_9.setText(_translate("MainWindow", "Personal phone number:"))
        self.label_10.setText(_translate("MainWindow", "Default access status:"))
        self.label_11.setText(_translate("MainWindow", "Address:"))
        self.submit.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = createAccount()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
